image: node:12.6.0
stages:
  - test
  - deploy

before_script:
  - yarn install

test:
  stage: test
  only:
    - master
  cache:
    paths:
      - node_modules/
  script:
    - yarn test:coverage

publish:
  stage: deploy
  only:
    - release
  except:
    changes:
      - package.json
  cache:
    paths:
      - node_modules/
  script:
    - git config user.name "${PUBLISH_USER_NAME}"
    - git config user.email "${PUBLISH_USER_EMAIL}"
    - yarn build:publish
    - npm version patch -m "publish version %s"
    - npm publish
    - git push https://${PUBLISH_USER_NAME}:${PUBLISH_USER_TOKEN}@gitlab.com/littlepy/littlepy.git HEAD:release --follow-tags
