export enum RowType {
  AssignmentOperator = 'AssignmentOperator',
  FunctionCall = 'FunctionCall',
  ForCycle = 'ForCycle',
  WhileCycle = 'WhileCycle',
  TryBlock = 'TryBlock',
  ExceptBlock = 'ExceptBlock',
  FinallyBlock = 'FinallyBlock',
  Raise = 'Raise',
  FunctionDefinition = 'FunctionDefinition',
  Comment = 'Comment',
  Unknown = 'Unknown',
  IfBlock = 'IfBlock',
  ElseBlock = 'ElseBlock',
  ElifBlock = 'ElifBlock',
  Import = 'Import',
  ImportFrom = 'ImportFrom',
  ImportAs = 'ImportAs',
  Pass = 'Pass',
  Return = 'Return',
  Expression = 'Expression',
  Continue = 'Continue',
  Break = 'Break',
  Yield = 'Yield',
  With = 'With',
  Del = 'Del',
}
