/* eslint-disable @typescript-eslint/camelcase */

export enum PythonErrorType {
  // LexicalAnalyzer errors
  UnknownChar,
  MismatchedIndent,
  UnknownEscapeChar,

  // Compiler errors
  BlockExpectedColon,
  IncompleteForDefinition,
  ForExpectedArgument,
  ForExpectedIn,
  IncompleteWhileDefinition,
  IncompleteFunctionDeclaration,
  ExpectedFunctionName,
  ExpectedFunctionArgumentList,
  ExpectedArgumentName,
  IncompleteFunctionArgumentList,
  ExpectedEndOfFunctionDef,
  ExpectedEndOfFunctionCall,
  IncompleteClassDeclaration,
  IncorrectInheritanceList,
  ExpectedClassName,
  ExpectedBinaryOperator,
  ExpectedUnaryOperatorOrArgument,
  ExpectedExpressionValue,
  ExpectedRightOperand,
  UnexpectedEndOfCall,
  ExpectedNamedArgumentNameInCall,
  OrderedArgumentAfterNamed,
  ExpectedEndOfIndexer,
  ExpectedEndOfExpression,
  ExpectedListDefinition,
  ExpectedListExpression,
  ExpectedEndOfListDefinition,
  ListExpectedCommaOrRightSquareBracket,
  ComprehensionExpectedIdentifier,
  ComprehensionExpectedInKeyword,
  ComprehensionNoArguments,
  ExpectedTupleBody,
  ExpectedTupleEnd,
  ExpectedSetBody,
  SetMixedWithAndWithoutColon,
  ExpectedStringLiteralInSet,
  ExpectedSetEnd,
  ConditionNoIfArgument,
  Error_Compiler_IfExpressionExpectedElse,
  ExpectedLiteral,
  UnexpectedBlockEnd,
  BlockInCombinedLine,
  Error_Compiler_CannotFindIfForElseOrElsif,
  Error_Compiler_ExpectingExceptOrFinallyAfterTry,
  Error_Compiler_CannotFindTryForExceptOrFinally,
  Error_Compiler_CannotFindIfOrElifForElif,
  Error_Compiler_CannotFindIfOrElifForElse,
  Error_Compiler_IncompleteImportDefinition,
  Error_Compiler_IncompleteImportFromDefinition,
  Error_Compiler_ImportFromDefinitionIsTooLong,
  Error_Compiler_ImportFromExpectedImport,
  Error_Compiler_ImportFromExpectedIdentifier,
  Error_Compiler_ImportDefinitionIsTooLong,
  Error_Compiler_ImportExpectedIdentifier,
  Error_Compiler_ImportExpectedAsIdentifier,
  Error_Compiler_PassHasNoArguments,
  Error_Compiler_BreakHasNoArguments,
  Error_Compiler_ContinueHasNoArguments,
  Error_Compiler_RaiseExpectedEndOfLine,
  Error_Compiler_ReturnOrYieldExpectedEndOfLine,
  Error_Compiler_ExceptExpectedTryOrExcept,
  Error_Compiler_ExceptExpectedRightBracket,
  Error_Compiler_ExceptExpectedIdentifierAfterAs,
  Error_Compiler_ExceptExpectedIdentifier,
  Error_Compiler_FinallyCannotFindExceptOrTry,
  Error_Compiler_FunctionCallExpectedArguments,
  Error_Compiler_FunctionExpectedCommaOrRightBracket,
  Error_Compiler_FunctionExpectedEndOfArguments,
  Error_Compiler_ExceptExpectedArguments,
  Error_Compiler_ExpectedExpression,
  Error_Compiler_ExpectedEndOfExpression,
  Error_Compiler_MixingAugmentedOperators,
  Error_Compiler_ExpectedYieldExpression,
  ErrorUnexpectedScenario_CodeGenerator_UnknownUnaryOperator,
  ErrorUnexpectedScenario_CodeGenerator_UnknownBinaryOperator,
  Error_Compiler_ExpectedEndOfIdentifierForDel,
  Error_Compiler_ExpectedIdentifierForDel,
  ErrorUnexpectedScenario_01,
  ErrorUnexpectedScenario_02,
  ErrorUnexpectedScenario_03,
  ErrorUnexpectedScenario_04,
}

export const ErrorCodeToTitle = {
  [PythonErrorType.UnknownChar]: 'unknownChar',
  [PythonErrorType.MismatchedIndent]: 'mismatchedIndent',
  [PythonErrorType.UnknownEscapeChar]: 'unknownEscapeChar',
  [PythonErrorType.IncompleteForDefinition]: 'incompleteForDefinition',
  [PythonErrorType.ForExpectedArgument]: 'forExpectedArgument',
  [PythonErrorType.ForExpectedIn]: 'forExpectedInKeyword',
  [PythonErrorType.BlockExpectedColon]: 'blockExpectedColon',
  [PythonErrorType.IncompleteWhileDefinition]: 'whileIncomplete',
  [PythonErrorType.IncompleteFunctionDeclaration]: 'functionDeclarationIncomplete',
  [PythonErrorType.ExpectedFunctionName]: 'functionDeclarationExpectedIdentifier',
  [PythonErrorType.ExpectedFunctionArgumentList]: 'functionDeclarationExpectedOpeningBracket',
  [PythonErrorType.ExpectedArgumentName]: 'functionDeclarationExpectedArgumentName',
  [PythonErrorType.IncompleteFunctionArgumentList]: 'functionDeclarationIncompleteArguments',
  [PythonErrorType.ExpectedEndOfFunctionDef]: 'functionDeclarationExpectedComma',
  [PythonErrorType.ExpectedEndOfFunctionCall]: 'functionCallExpectedComma',
  [PythonErrorType.IncompleteClassDeclaration]: 'classDeclarationIncomplete',
  [PythonErrorType.ExpectedClassName]: 'classDeclarationExpectedIdentifier',
  [PythonErrorType.IncorrectInheritanceList]: 'class-declaration-incorrect-inheritance',
  [PythonErrorType.ExpectedBinaryOperator]: 'expression-expected-binary-operator',
  [PythonErrorType.ExpectedUnaryOperatorOrArgument]: 'expression-expected-unary-operator-or-argument',
  [PythonErrorType.ExpectedExpressionValue]: 'expression-expected-value',
  [PythonErrorType.UnexpectedEndOfCall]: 'function-call-unexpected-end',
  [PythonErrorType.ExpectedNamedArgumentNameInCall]: 'function-call-expected-argument-name',
  [PythonErrorType.ExpectedEndOfIndexer]: 'expression-expected-end-indexer',
  [PythonErrorType.ExpectedEndOfExpression]: 'expression-unexpected-end',
  [PythonErrorType.ExpectedListDefinition]: 'list-expected-definition',
  [PythonErrorType.ExpectedListExpression]: 'list-expected-expression',
  [PythonErrorType.ExpectedEndOfListDefinition]: 'list-expected-end',
  [PythonErrorType.ListExpectedCommaOrRightSquareBracket]: 'list-expected-comma',
  [PythonErrorType.ComprehensionExpectedIdentifier]: 'comprehension-expected-identifier',
  [PythonErrorType.ComprehensionExpectedInKeyword]: 'comprehension-expected-in',
  [PythonErrorType.ComprehensionNoArguments]: 'comprehension-no-arguments',
  [PythonErrorType.ExpectedTupleBody]: 'tuple-expected-body',
  [PythonErrorType.ExpectedTupleEnd]: 'tuple-expected-comma',
  [PythonErrorType.ExpectedSetBody]: 'set-expected-body',
  [PythonErrorType.SetMixedWithAndWithoutColon]: 'set-mixed-with-without-colon',
  [PythonErrorType.ExpectedStringLiteralInSet]: 'set-expected-string-literal',
  [PythonErrorType.ExpectedSetEnd]: 'set-expected-comma',
  [PythonErrorType.ConditionNoIfArgument]: 'if-expression-no-if-argument',
  [PythonErrorType.Error_Compiler_IfExpressionExpectedElse]: 'if-expression-expected-else',
  [PythonErrorType.ExpectedLiteral]: 'value-expected-literal',
  [PythonErrorType.UnexpectedBlockEnd]: 'unexpected-block-end',
  [PythonErrorType.BlockInCombinedLine]: 'block-in-combined',
  [PythonErrorType.Error_Compiler_CannotFindIfForElseOrElsif]: 'else-elif-no-if',
  [PythonErrorType.Error_Compiler_ExpectingExceptOrFinallyAfterTry]: 'try-without-except-finally',
  [PythonErrorType.Error_Compiler_CannotFindTryForExceptOrFinally]: 'except-finally-without-try',
  [PythonErrorType.Error_Compiler_CannotFindIfOrElifForElif]: 'no-if-or-elif-for-elif',
  [PythonErrorType.Error_Compiler_CannotFindIfOrElifForElse]: 'no-if-or-elif-for-else',
  [PythonErrorType.Error_Compiler_IncompleteImportDefinition]: 'import-incomplete',
  [PythonErrorType.Error_Compiler_ImportDefinitionIsTooLong]: 'import-too-long',
  [PythonErrorType.Error_Compiler_ImportExpectedIdentifier]: 'import-expected-identifier',
  [PythonErrorType.Error_Compiler_ImportExpectedAsIdentifier]: 'import-expected-as-identifier',
  [PythonErrorType.Error_Compiler_IncompleteImportFromDefinition]: 'import-from-incomplete',
  [PythonErrorType.Error_Compiler_ImportFromDefinitionIsTooLong]: 'import-from-too-long',
  [PythonErrorType.Error_Compiler_ImportFromExpectedImport]: 'import-from-expected-import',
  [PythonErrorType.Error_Compiler_ImportFromExpectedIdentifier]: 'import-from-expected-identifier',
  [PythonErrorType.Error_Compiler_PassHasNoArguments]: 'pass-with-arguments',
  [PythonErrorType.Error_Compiler_ContinueHasNoArguments]: 'continue-with-arguments',
  [PythonErrorType.Error_Compiler_BreakHasNoArguments]: 'break-with-arguments',
  [PythonErrorType.Error_Compiler_RaiseExpectedEndOfLine]: 'raise-expected-end',
  [PythonErrorType.Error_Compiler_ReturnOrYieldExpectedEndOfLine]: 'keyword-expression-expected-end',
  [PythonErrorType.Error_Compiler_ExceptExpectedTryOrExcept]: 'expect-expected-try-or-except',
  [PythonErrorType.Error_Compiler_ExceptExpectedRightBracket]: 'except-expected-right-bracket',
  [PythonErrorType.Error_Compiler_ExceptExpectedIdentifierAfterAs]: 'except-expected-identifier',
  [PythonErrorType.Error_Compiler_ExceptExpectedIdentifier]: 'except-expected-identifier',
  [PythonErrorType.Error_Compiler_FinallyCannotFindExceptOrTry]: 'finally-no-except-or-try',
  [PythonErrorType.Error_Compiler_FunctionCallExpectedArguments]: 'function-call-expected-arguments',
  [PythonErrorType.Error_Compiler_FunctionExpectedCommaOrRightBracket]: 'function-call-expected-comma-2',
  [PythonErrorType.Error_Compiler_FunctionExpectedEndOfArguments]: 'function-call-expected-end',
  [PythonErrorType.Error_Compiler_ExceptExpectedArguments]: 'except-expected-arguments',
  [PythonErrorType.Error_Compiler_ExpectedExpression]: 'expected-expression',
  [PythonErrorType.Error_Compiler_ExpectedYieldExpression]: 'expected-yield-expression',
  [PythonErrorType.Error_Compiler_ExpectedEndOfExpression]: 'expected-end-expression',
  [PythonErrorType.ErrorUnexpectedScenario_CodeGenerator_UnknownUnaryOperator]: 'unexpected-scenario-unary',
  [PythonErrorType.ErrorUnexpectedScenario_CodeGenerator_UnknownBinaryOperator]: 'unexpected-scenario-binary',
  [PythonErrorType.ExpectedRightOperand]: 'expected-right-operand',
  [PythonErrorType.OrderedArgumentAfterNamed]: 'ordered-after-named',
  [PythonErrorType.ErrorUnexpectedScenario_01]: 'unexpected-scenario',
  [PythonErrorType.ErrorUnexpectedScenario_02]: 'unexpected-scenario',
  [PythonErrorType.ErrorUnexpectedScenario_03]: 'unexpected-scenario',
  [PythonErrorType.ErrorUnexpectedScenario_04]: 'unexpected-scenario',
  [PythonErrorType.Error_Compiler_ExpectedEndOfIdentifierForDel]: 'expected-del-end',
  [PythonErrorType.Error_Compiler_ExpectedIdentifierForDel]: 'expected-del-identifier',
};
